CREATE TABLE PRODUTO (
	COD_PRODUTO char(4) NOT NULL PRIMARY KEY,
	DES_PRODUTO varchar(30) NULL,
	STA_STATUS char(1) NULL
);

CREATE TABLE PRODUTO_COSIF (
	COD_PRODUTO char(4) NOT NULL,
	COD_COSIF char(11) NOT NULL,
	COD_CLASSIFICACAO char(6) NULL,
	STA_STATUS char(1) NULL,
	CONSTRAINT FK_COD_PRODUTO FOREIGN KEY (COD_PRODUTO) REFERENCES PRODUTO(COD_PRODUTO),
	CONSTRAINT PK_COD_PRODUTO_COD_COSIF PRIMARY KEY (COD_PRODUTO, COD_COSIF)
);

CREATE TABLE MOVIMENTO_MANUAL (
	DAT_MES numeric(2, 0) NOT NULL,
	DAT_ANO numeric(4, 0) NOT NULL,
	NUM_LANCAMENTO numeric(18, 0) NOT NULL,
	COD_PRODUTO char(4) NOT NULL,
	COD_COSIF char(11) NOT NULL,
	DES_DESCRICAO varchar(50) NOT NULL,
	DAT_MOVIMENTO smalldatetime NOT NULL,
	COD_USUARIO varchar(15) NOT NULL,
	VAL_VALOR numeric(18, 2) NOT NULL,
	CONSTRAINT FK_COD_PRODUTO_COD_COSIF FOREIGN KEY (COD_PRODUTO, COD_COSIF) REFERENCES PRODUTO_COSIF(COD_PRODUTO, COD_COSIF),
	CONSTRAINT PK_DAT_MES_DAT_ANO_NUM_LANCAMENTO_COD_PRODUTO_COD_COSIF PRIMARY KEY (DAT_MES, DAT_ANO, NUM_LANCAMENTO, COD_PRODUTO, COD_COSIF)
);
